### ISSUE TITLE
API Credentials

### ISSUE THREAD

**Issue by NocElsynet** [modrisb/chirp#1]
congratulations for the work done.
 what do you mean as :"ChirpStack server credentials required, including API key used for connection authentication". could you post an example? chirpstack v4 has swagger bees. on port 8090, on 8080 there is the application server, I have tried all ways, but the connection key*. it always gives me the error: length of value must be at least 210
thanks in advance for your help.

**Comment by modrisb** [comment]
This was code issue - wrong constraints, fixed in 1.0.9. There is add-on version of this integration in https://github.com/modrisb/chirpha, no need for connection key for this implementation
